//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public article()
        {
            this.comment = new HashSet<comment>();
            this.user_fav = new HashSet<user_fav>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public int category { get; set; }
        public int author { get; set; }
        public int state { get; set; }
        public int views { get; set; }
        public Nullable<int> rating { get; set; }
        public int rate_count { get; set; }
        public string link { get; set; }
        public System.DateTime timestamp { get; set; }
    
        public virtual article_state article_state { get; set; }
        public virtual user user { get; set; }
        public virtual article_type article_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_fav> user_fav { get; set; }
    }
}
