//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class faq
    {
        public int id { get; set; }
        public string question { get; set; }
        public string answer { get; set; }
        public int asker_id { get; set; }
        public Nullable<int> respondent_id { get; set; }
        public System.DateTime q_timestamp { get; set; }
        public Nullable<System.DateTime> a_timestamp { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
