//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GamesJournalEntities : DbContext
    {
        public GamesJournalEntities()
            : base("name=GamesJournalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<article> article { get; set; }
        public virtual DbSet<article_state> article_state { get; set; }
        public virtual DbSet<article_type> article_type { get; set; }
        public virtual DbSet<comment> comment { get; set; }
        public virtual DbSet<compatible_game> compatible_game { get; set; }
        public virtual DbSet<complaint> complaint { get; set; }
        public virtual DbSet<faq> faq { get; set; }
        public virtual DbSet<feedback> feedback { get; set; }
        public virtual DbSet<game> game { get; set; }
        public virtual DbSet<game_type> game_type { get; set; }
        public virtual DbSet<latest_news> latest_news { get; set; }
        public virtual DbSet<pc_specs> pc_specs { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<user_fav> user_fav { get; set; }
        public virtual DbSet<user_type> user_type { get; set; }
    }
}
