//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class game
    {
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime release_date { get; set; }
        public string description { get; set; }
        public string links { get; set; }
        public int type { get; set; }
        public int publisher { get; set; }
    
        public virtual game_type game_type { get; set; }
        public virtual user user { get; set; }
    }
}
